apiVersion: v1
kind: Service
metadata:
  labels:
    run: nginx
  name: myservice 
spec:
  ports:
  - nodePort: 32704
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    run: nginx
  type: LoadBalancer
