apiVersion: v1
kind: Pod
metadata:
  name: nexus
  # namespace: nginx
  labels:
    app: nexus
spec:
  # nodeName: gke-myk8s-default-pool-3636d28a-h9bd
  containers:
  - name: nexus
    image: nginx
    resources:
      requests:
        memory: "100Mi"
        cpu: "100m"
      limits:
        memory: "128Mi"
        cpu: "500m"