apiVersion: v1
kind: Pod
metadata:
  name: mypod
  # namespace: nginx
  labels:
    app: nginx
spec:
  # nodeName: gke-myk8s-default-pool-3636d28a-h9bd
  containers:
  - name: myfrontend
    image: nginx
    volumeMounts:
    - name: mypd
      mountPath: "/var/www/html"
  volumes:
    - name:  mypd
      persistentVolumeClaim:
        claimName: pvc-nginx
